import { CategoryType, ExpenseCategoriesType } from "@/type";
import * as Icons from "phosphor-react-native";

export const expenseCategories: ExpenseCategoriesType = {
  groceries: {
    label: "Food",
    value: "food",
    icon: Icons.Hamburger,
    bgColor: "#22c55e",
  },
  onlineshop: {
    label: "Online Shop",
    value: "OnlineShop",
    icon: Icons.ShoppingCart,
    bgColor: "#0ea5e9",
  },
  rent: {
    label: "Rent",
    value: "rent",
    icon: Icons.House,
    bgColor: "#1e3a8a",
  },
  utilities: {
    label: "Utilities",
    value: "utilities",
    icon: Icons.Lightning,
    bgColor: "#facc15",
  },
  transport: {
    label: "Transport",
    value: "transport",
    icon: Icons.Train,
    bgColor: "#2563eb",
  },
  fuel: {
    label: "Fuel",
    value: "fuel",
    icon: Icons.GasPump,
    bgColor: "#ea580c",
  },
  car: {
    label: "Car",
    value: "car",
    icon: Icons.Car,
    bgColor: "#f59e0b",
  },
  bills: {
    label: "Bills",
    value: "bill",
    icon: Icons.Invoice,
    bgColor: "#e11d48",
  },
  healthcare: {
    label: "Healthcare",
    value: "healthcare",
    icon: Icons.Heartbeat,
    bgColor: "#dc2626",
  },
  insurance: {
    label: "Insurance",
    value: "insurance",
    icon: Icons.ShieldCheck,
    bgColor: "#0891b2",
  },
  dining: {
    label: "Dining Out",
    value: "dining",
    icon: Icons.Cheers,
    bgColor: "#9333ea",
  },
  subscriptions: {
    label: "Subscriptions",
    value: "subscriptions",
    icon: Icons.Monitor,
    bgColor: "#14b8a6",
  },
  subscriptionsEntertainment: {
    label: "Entertainment Subscriptions",
    value: "subscriptionsEntertainment",
    icon: Icons.MonitorPlay,
    bgColor: "#7c3aed",
  },
  shopping: {
    label: "Shopping",
    value: "shopping",
    icon: Icons.ShoppingCartSimple,
    bgColor: "#ec4899",
  },
  clothing: {
    label: "Clothing",
    value: "clothing",
    icon: Icons.TShirt,
    bgColor: "#f472b6",
  },
  beauty: {
    label: "Beauty",
    value: "beauty",
    icon: Icons.HighlighterCircle,
    bgColor: "#db2777",
  },
  travel: {
    label: "Travel",
    value: "travel",
    icon: Icons.Airplane,
    bgColor: "#0284c7",
  },
  education: {
    label: "Education",
    value: "education",
    icon: Icons.Student,
    bgColor: "#16a34a",
  },
  entertainment: {
    label: "Entertainment",
    value: "entertainment",
    icon: Icons.PersonSimpleThrow,
    bgColor: "#f43f5e",
  },
  gifts: {
    label: "Gifts",
    value: "gifts",
    icon: Icons.Gift,
    bgColor: "#fb923c",
  },
  savings: {
    label: "Savings",
    value: "savings",
    icon: Icons.PiggyBank,
    bgColor: "#15803d",
  },
  fitness: {
    label: "Fitness",
    value: "fitness",
    icon: Icons.Barbell,
    bgColor: "#10b981",
  },
  personalCare: {
    label: "Personal Care",
    value: "personalCare",
    icon: Icons.Scissors,
    bgColor: "#eab308",
  },
  pets: {
    label: "Pets",
    value: "pets",
    icon: Icons.PawPrint,
    bgColor: "#a855f7",
  },
  charity: {
    label: "Charity",
    value: "charity",
    icon: Icons.Heart,
    bgColor: "#ef4444",
  },
  events: {
    label: "Events",
    value: "events",
    icon: Icons.Calendar,
    bgColor: "#3b82f6",
  },
  homeImprovement: {
    label: "Home Improvement",
    value: "homeImprovement",
    icon: Icons.Hammer,
    bgColor: "#f97316",
  },
  electronics: {
    label: "Electronics",
    value: "electronics",
    icon: Icons.ComputerTower,
    bgColor: "#0ea5e9",
  },
  hobbies: {
    label: "Hobbies",
    value: "hobbies",
    icon: Icons.PaintBrush,
    bgColor: "#fbbf24",
  },
  investments: {
    label: "Investments",
    value: "investments",
    icon: Icons.ChartLineUp,
    bgColor: "#22c55e",
  },
  taxes: {
    label: "Taxes",
    value: "taxes",
    icon: Icons.Receipt,
    bgColor: "#b91c1c",
  },
  entertainmentTickets: {
    label: "Tickets",
    value: "entertainmentTickets",
    icon: Icons.Ticket,
    bgColor: "#d946ef",
  },
  software: {
    label: "Software & Apps",
    value: "software",
    icon: Icons.Code,
    bgColor: "#06b6d4",
  },
  books: {
    label: "Books",
    value: "books",
    icon: Icons.Book,
    bgColor: "#1d4ed8", 
  },
  music: {
    label: "Music",
    value: "music",
    icon: Icons.MusicNote,
    bgColor: "#9333ea",
  },
  movies: {
    label: "Movies",
    value: "movies",
    icon: Icons.FilmReel,
    bgColor: "#be123c",
  },
  coffee: {
    label: "Coffee & Snacks",
    value: "coffee",
    icon: Icons.Coffee,
    bgColor: "#78350f",
  },
  stationery: {
    label: "Stationery",
    value: "stationery",
    icon: Icons.Pencil,
    bgColor: "#f59e0b",
  },
  utilitiesInternet: {
    label: "Internet",
    value: "utilitiesInternet",
    icon: Icons.WifiHigh,
    bgColor: "#2563eb",
  },
  utilitiesPhone: {
    label: "Phone",
    value: "utilitiesPhone",
    icon: Icons.Phone,
    bgColor: "#10b981",
  },
  homeDecor: {
    label: "Home Decor",
    value: "homeDecor",
    icon: Icons.PaintBrush,
    bgColor: "#fb7185",
  },
  other: {
    label: "Other",
    value: "other",
    icon: Icons.DotsThree,
    bgColor: "#6b7280", 
  },
};

export const incomeCategories: ExpenseCategoriesType = {
  salary: {
    label: "Salary",
    value: "salary",
    icon: Icons.Briefcase,
    bgColor: "#16a34a",
  },
  freelance: {
    label: "Freelance",
    value: "freelance",
    icon: Icons.Laptop,
    bgColor: "#0ea5e9",
  },
  business: {
    label: "Business",
    value: "business",
    icon: Icons.Storefront,
    bgColor: "#f97316",
  },
  investments: {
    label: "Investments",
    value: "investments",
    icon: Icons.ChartLineUp,
    bgColor: "#22c55e",
  },
  rental: {
    label: "Rental Income",
    value: "rental",
    icon: Icons.House,
    bgColor: "#1e3a8a",
  },
  dividends: {
    label: "Dividends",
    value: "dividends",
    icon: Icons.CurrencyDollar,
    bgColor: "#facc15",
  },
  gifts: {
    label: "Gifts",
    value: "gifts",
    icon: Icons.Gift,
    bgColor: "#fb923c",
  },
  bonus: {
    label: "Bonus",
    value: "bonus",
    icon: Icons.Trophy,
    bgColor: "#f43f5e",
  },
  pension: {
    label: "Pension",
    value: "pension",
    icon: Icons.Wallet,
    bgColor: "#10b981",
  },
  refund: {
    label: "Refunds",
    value: "refund",
    icon: Icons.ArrowCounterClockwise,
    bgColor: "#2563eb",
  },
  royalty: {
    label: "Royalties",
    value: "royalty",
    icon: Icons.MusicNote,
    bgColor: "#9333ea",
  },
  affiliate: {
    label: "Affiliate Income",
    value: "affiliate",
    icon: Icons.LinkSimple,
    bgColor: "#7c3aed",
  },
  tips: {
    label: "Tips",
    value: "tips",
    icon: Icons.HandCoins,
    bgColor: "#eab308",
  },
  lottery: {
    label: "Lottery/Winnings",
    value: "lottery",
    icon: Icons.Star,
    bgColor: "#f59e0b",
  },
  commission: {
    label: "Commission",
    value: "commission",
    icon: Icons.Money,
    bgColor: "#0891b2",
  },
  reimbursement: {
    label: "Reimbursement",
    value: "reimbursement",
    icon: Icons.ArrowCircleRight,
    bgColor: "#6b7280",
  },
  onlineCourses: {
    label: "Online Courses",
    value: "onlineCourses",
    icon: Icons.DesktopTower,
    bgColor: "#ec4899",
  },
  cryptocurrency: {
    label: "Cryptocurrency",
    value: "cryptocurrency",
    icon: Icons.CurrencyBtcIcon,
    bgColor: "#f97316",
  },
  grants: {
    label: "Grants",
    value: "grants",
    icon: Icons.Medal,
    bgColor: "#22c55e",
  },
  other: {
    label: "Other Income",
    value: "other",
    icon: Icons.DotsThree,
    bgColor: "#6b7280",
  },
};

export const incomeCategory: CategoryType = {
  label: "Income",
  value: "income",
  icon: Icons.CurrencyDollar,
  bgColor: "#16a34a", 
};

export const transactionTypes = [
  { label: "Expense", value: "expense" },
  { label: "Income", value: "income" },
];
